---
title: "XGBoost"
output: html_notebook
---

# Let's attempt to build a model that can predict EO Preeclampsia from SNP data alone (spoiler alert: no success)


```{r}
source("setup.r")
library(xgboost)
library(caTools)
conflict_prefer("union", "dplyr")
conflict_prefer("colnames", "base")
conflict_prefer("as.numeric", "base")
```


```{r}
clinical = pe.getClinicalInfo()
domRecMatrix = pe.getNumericAlleleMatrix()
domRecMatrix[1:5,1:5]
```

```{r}
draw_confusion_matrix <- function(cm) {
  
  total = sum(cm$table)
  res <- as.numeric(cm$table)
  
  # Generate color gradients. Palettes come from RColorBrewer.
  greenPalette = c("#F7FCF5","#E5F5E0","#C7E9C0","#A1D99B","#74C476","#41AB5D","#238B45","#006D2C","#00441B")
  redPalette = c("#FFF5F0","#FEE0D2","#FCBBA1","#FC9272","#FB6A4A","#EF3B2C","#CB181D","#A50F15","#67000D")
  getColor = function (greenOrRed = "green", amount = 0) {
    if (amount == 0)
      return("#FFFFFF")
    palette = greenPalette
    if (greenOrRed == "red")
      palette = redPalette
    colorRampPalette(palette)(100)[10 + ceiling(90 * amount / total)]
  }

  # set the basic layout
  layout(matrix(c(1,1,2)))
  par(mar=c(2,2,2,2))
  plot(c(100, 345), c(300, 450), type = "n", xlab="", ylab="", xaxt='n', yaxt='n')
  title('CONFUSION MATRIX', cex.main=2)
  
  # create the matrix 
  classes = colnames(cm$table)
  rect(150, 430, 240, 370, col=getColor("green", res[1]))
  text(195, 435, classes[1], cex=1.2)
  rect(250, 430, 340, 370, col=getColor("red", res[3]))
  text(295, 435, classes[2], cex=1.2)
  text(125, 370, 'Predicted', cex=1.3, srt=90, font=2)
  text(245, 450, 'Actual', cex=1.3, font=2)
  rect(150, 305, 240, 365, col=getColor("red", res[2]))
  rect(250, 305, 340, 365, col=getColor("green", res[4]))
  text(140, 400, classes[1], cex=1.2, srt=90)
  text(140, 335, classes[2], cex=1.2, srt=90)
  
  # add in the cm results
  text(195, 400, res[1], cex=1.6, font=2, col='white')
  text(195, 335, res[2], cex=1.6, font=2, col='white')
  text(295, 400, res[3], cex=1.6, font=2, col='white')
  text(295, 335, res[4], cex=1.6, font=2, col='white')
  
  # add in the specifics 
  plot(c(100, 0), c(100, 0), type = "n", xlab="", ylab="", main = "DETAILS", xaxt='n', yaxt='n')
  text(10, 85, names(cm$byClass[1]), cex=1.2, font=2)
  text(10, 70, round(as.numeric(cm$byClass[1]), 3), cex=1.2)
  text(30, 85, names(cm$byClass[2]), cex=1.2, font=2)
  text(30, 70, round(as.numeric(cm$byClass[2]), 3), cex=1.2)
  text(50, 85, names(cm$byClass[5]), cex=1.2, font=2)
  text(50, 70, round(as.numeric(cm$byClass[5]), 3), cex=1.2)
  text(70, 85, names(cm$byClass[6]), cex=1.2, font=2)
  text(70, 70, round(as.numeric(cm$byClass[6]), 3), cex=1.2)
  text(90, 85, names(cm$byClass[7]), cex=1.2, font=2)
  text(90, 70, round(as.numeric(cm$byClass[7]), 3), cex=1.2)
  
  # add in the accuracy information 
  text(30, 35, names(cm$overall[1]), cex=1.5, font=2)
  text(30, 20, round(as.numeric(cm$overall[1]), 3), cex=1.4)
  text(70, 35, names(cm$overall[2]), cex=1.5, font=2)
  text(70, 20, round(as.numeric(cm$overall[2]), 3), cex=1.4)
}

```



```{r}
combined = cbind(clinical %>% select(preeclampsia), domRecMatrix)
combined$preeclampsia = as.factor(combined$preeclampsia)

split <- sample.split(clinical$preeclampsia, SplitRatio = 0.8)
training_set = subset(combined, split == TRUE)
validation_set = subset(combined, split == FALSE)

dTrain <- xgb.DMatrix(as.matrix(training_set[-1]), label = as.matrix(training_set[1]))
dValidation <- xgb.DMatrix(as.matrix(validation_set[-1]), label = as.matrix(validation_set[1]))
dwatchlist <- list(eval = dValidation, train = dTrain)

params <- list(eta = 0.1, max_depth = 2,  objective = "binary:logistic")
classifier <- xgb.train(data = dTrain, params = params, save_period = 100, watchlist = dwatchlist, 
  label = training_set[1], early_stopping_rounds = 5, nrounds = 50)

y_pred <- predict(classifier, newdata = as.matrix(validation_set[-1])) %>%  round

actual = as.data.frame(validation_set)[, 1]
importance = xgb.importance(colnames(combined)[-1], model = classifier)
ggplot(importance[1:10,], aes(x = Feature, y = Gain)) + geom_col()

cm = caret::confusionMatrix(factor(y_pred), factor(actual))
draw_confusion_matrix(cm)
print(importance[1:10,])
cm
```

# Try cross validation

```{r}
clinical = pe.getClinicalInfo()
domRecMatrix = pe.getNumericAlleleMatrix()
params <- list(eta = 0.02, max_depth = 2,  objective = "binary:logistic")
booster = xgb.cv(params, domRecMatrix, 30, nfold = 5, label = clinical$preeclampsia)
booster$evaluation_log[booster$best_iteration]$test_error_mean
```

# Let's try to predict EOPE on clinical data as a sanity check. We expect 0 error/100% accuracy.

```{r}
clinicalNumeric = as.matrix(pe.getClinicalAsNumerics())
training_set = subset(clinicalNumeric, split == TRUE)
validation_set = subset(clinicalNumeric, split == FALSE)
dTrain <- xgb.DMatrix(training_set[,-1], label = training_set[,1])

params <- list(eta = 0.3, max_depth = 1, objective = "binary:logistic")
classifier <- xgb.train(params, dTrain, 20)

y_pred <- predict(classifier, newdata = validation_set[,-1]) %>% round

actual = as.data.frame(validation_set)[, 1]
importance = xgb.importance(colnames(clinicalNumeric)[-1], model = classifier)
ggplot(importance[1:10,], aes(x = Feature, y = Gain)) + geom_col()

cm = caret::confusionMatrix(factor(y_pred), factor(actual))
draw_confusion_matrix(cm)
print(importance[1:10,])
cm
```
